name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      pull-requests: "write"
    steps:
      - name: "Checkout do código"
        uses: "actions/checkout@v4"
      - name: "Gemini PR Reviewer"
          # Você pode fixar no commit exato ou na versão.
          # uses: vivek180905/Gemini-AI-PR-Reviewer@35f216080d352aeae537fb287d1a0ff3086802e5
        uses: "vivek180905/Gemini-AI-PR-Reviewer@v1.0.1"
        with:
        # Token do GitHub para acessar o repositório e publicar comentários.
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        # Chave de API para o Google Gemini:
        gemini-api-key: ${{ secrets.GEMINI_API_KEY }}